[package]
name = "rust-precise"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
validator = { version = "0.19.0", features = ["derive"] }

[dev-dependencies]
wiremock = "0.6.2"
