[application]
port = 8080
host = "127.0.0.1"

[database]
host = "192.168.20.221"
port = 3306
username = "paldi"
password = "masihpemula"
database_name = "precise"

[test_client]
base_url = "localhost"